### ISSUE TITLE
Tidal Connect [not supported]

### ISSUE THREAD

**Issue by modellbobby** [RoPieee/ropieee-kernel#3]
Hey guys,

can you look into this working Tidal connect implemetation and include this into RopieeeXL ?

https://github.com/shawaj/HiTide

Kind regards

**Comment by modellbobby** [comment]
works like a charme and running this currently with my Allo Digione Hat

**Comment by jacobwod** [comment]
Hi @spockfish and thank you for the amazing work you put into RoPieee!

I understand that this is not the place where userland software (such as the proposed HiTide), should be discussed, but this looks to be the only way to reach out to you. 

Any opinions on **HiTide**? It should be doable in a manner similar to how you've packaged Librespot or Shairport in the current releases of RoPieee XL. It would indeed be a fantastic addition! 👍

**Comment by jacobwod** [comment]
I did a quick test on current (Linux ropieee 5.4.83-5-SPCKFSH-v7+) RoPieee by cloning the Tidal Connect service into `/usr/ifi`:
```
mkdir /usr/ifi
git clone https://github.com/shawaj/ifi-tidal-release
```

Looking into the systemd service script, the command to run the service would be something like: 
```
/usr/ifi/ifi-tidal-release/bin/tidal_connect_application \
                                --tc-certificate-path "/usr/ifi/ifi-tidal-release/id_certificate/IfiAudio_ZenStream.dat" \
                                -f "HiTide RasPi Streamer" \
                                --codec-mpegh true \
                                --codec-mqa false \
                                --model-name "HiTide RasPi Streamer" \
                                --disable-app-security false \
                                --disable-web-security false \
                                --enable-mqa-passthrough false \
                                --log-level 3 \
                                --enable-websocket-log "0"
```

So I tried it. It did complain about missing libraries, which I (naively) tried to fix by linking the existing versions (newer than required) to the ones required by tidal-connect. E.g.:
```
ln -s libavutil.so.56.14.100 libavutil.so.55
```

There were a handful of libraries to "fix" that way. When I was done, I tried running again, but it turns out that symbolic linking of libraries isn't enough, and we must provide the required versions:
```
# Output from tidal_connect_application
/usr/ifi/ifi-tidal-release/bin/tidal_connect_application: /usr/lib/libswresample.so.2: version `LIBSWRESAMPLE_2' not found (required by /usr/ifi/ifi-tidal-release/bin/tidal_connect_application)
/usr/ifi/ifi-tidal-release/bin/tidal_connect_application: /usr/lib/libavcodec.so.57: version `LIBAVCODEC_57' not found (required by /usr/ifi/ifi-tidal-release/bin/tidal_connect_application)
/usr/ifi/ifi-tidal-release/bin/tidal_connect_application: /usr/lib/libavutil.so.55: version `LIBAVUTIL_55' not found (required by /usr/ifi/ifi-tidal-release/bin/tidal_connect_application)
/usr/ifi/ifi-tidal-release/bin/tidal_connect_application: /usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /usr/ifi/ifi-tidal-release/bin/tidal_connect_application)
/usr/ifi/ifi-tidal-release/bin/tidal_connect_application: /usr/lib/libavformat.so.57: version `LIBAVFORMAT_57' not found (required by /usr/ifi/ifi-tidal-release/bin/tidal_connect_application)
```

**Any idea on how to add specific versions of those libraries to RoPieee?** The original solution uses APT, but it's not available on RoPieee (neither is `deb` nor `rpm` nor `opkg`), as far as I can tell. How can we add those libraries manually?

**Comment by spockfish** [comment]
As mentioned on the forum: I will not distribute illegal software.

**Comment by jacobwod** [comment]
You're absolutely right, I had no idea that ifi-tidal-release's legal status was unclear.
